services:
  unrealircd:
    image: unrealircd/unrealircd:6.1.0
    container_name: aetheron-unrealircd
    user: "${AETHERON_PUID}:${AETHERON_PGID}"
    volumes:
      - /home/ircd/unrealircd/data:/home/ircd/unrealircd/data
      - /home/ircd/unrealircd/conf:/home/ircd/unrealircd/conf
      - /home/ircd/unrealircd/ssl:/home/ircd/unrealircd/ssl
      - /home/khryon/logs/unrealircd:/home/ircd/unrealircd/logs
    ports:
      - "6697:6697/tcp"
      - "6997:6997/tcp"
    environment:
      - TZ=Europe/Berlin
    networks:
      - aetheron
    restart: unless-stopped
networks:
  aetheron:
    external: true
